apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: webapp1
        image: testapp/app1:v0.2
        command: ["/hli_app/sw/jboss/engine/tomcat/bin/start.sh"]
        args: ["-Dspring.config.location=file:///hli_app/sw/jboss/config/application_user1.yml"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp1-svc
  labels:
    app: webapp1
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: webapp1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp2
  template:
    metadata:
      labels:
        app: webapp2
    spec:
      containers:
      - name: webapp2
        image: testapp/app1:v0.2
        command: ["/hli_app/sw/jboss/engine/tomcat/bin/start.sh"]
        args: ["-Dapplication.yml.location=file:///hli_app/sw/jboss/config/application_user2.yml"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp2-svc
  labels:
    app: webapp2
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: webapp2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp3
  template:
    metadata:
      labels:
        app: webapp3
    spec:
      containers:
      - name: webapp3
        image: testapp/app1:v0.2
        command: ["/hli_app/sw/jboss/engine/tomcat/bin/start.sh"]
        args: ["-Dapplication.yml.location=file:///hli_app/sw/jboss/config/application_user3.yml"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp3-svc
  labels:
    app: webapp3
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: webapp3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp4
  template:
    metadata:
      labels:
        app: webapp4
    spec:
      containers:
      - name: webapp4
        image: testapp/app1:v0.2
        command: ["/hli_app/sw/jboss/engine/tomcat/bin/start.sh"]
        args: ["-Dapplication.yml.location=file:///hli_app/sw/jboss/config/application_user4.yml"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp4-svc
  labels:
    app: webapp4
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: webapp4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp5
  template:
    metadata:
      labels:
        app: webapp5
    spec:
      containers:
      - name: webapp5
        image: testapp/app1:v0.2
        command: ["/hli_app/sw/jboss/engine/tomcat/bin/start.sh"]
        args: ["-Dapplication.yml.location=file:///hli_app/sw/jboss/config/application_user5.yml"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp5-svc
  labels:
    app: webapp5
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: webapp5
---
