apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp5
  template:
    metadata:
      labels:
        app: webapp5
    spec:
      containers:
      - name: webapp5
        image: testapp/app1:v0.2
        command: ["/hli_app/sw/jboss/engine/tomcat/bin/start.sh"]
        args: ["-Dapplication.yml.location=file:///hli_app/sw/jboss/config/application_user5.yml"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp5-svc
  labels:
    app: webapp5
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: webapp5
---
