apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webapp1
  template:
    metadata:
      labels:
        name: webapp1
    spec:
      containers:
      - name: webapp1
        image: testapp/base:v0.1
        command: ["/hli_app/sw/jboss/engine/tomcat/bin/startup.sh"]
        ports:
        - containerPort: 8080
